# Task 3 – Text Preprocessing using Hugging Face Transformers

## Objective

The objective of this task is to preprocess textual descriptions using Hugging Face Transformers by converting flower descriptions into numerical representations suitable for text-to-image generation.

The workflow includes:

- Loading flower descriptions
- Tokenization
- Attention Mask generation
- Text Embedding generation
- Preparing embeddings for the image generation model

## Note

The Oxford-102 Flowers dataset does not provide natural-language captions for each image. Therefore, representative flower descriptions were created to demonstrate the Hugging Face text preprocessing pipeline, including tokenization, attention mask generation, embedding creation, and preparation for text-to-image generation.

In [2]:
from transformers import AutoTokenizer, AutoModel
import torch


In [3]:
print("Libraries imported successfully!")

Libraries imported successfully!


In [4]:
# Sample flower descriptions

flower_descriptions = [
    "A red rose with green leaves",
    "A bright yellow sunflower under sunlight",
    "A white lily blooming in a garden",
    "A pink lotus floating on water",
    "A purple orchid with long petals"
]

print("Flower Descriptions:\n")

for desc in flower_descriptions:
    print("-", desc)

Flower Descriptions:

- A red rose with green leaves
- A bright yellow sunflower under sunlight
- A white lily blooming in a garden
- A pink lotus floating on water
- A purple orchid with long petals


In [5]:
tokenizer = AutoTokenizer.from_pretrained("distilbert-base-uncased")

print("Tokenizer Loaded Successfully!")

config.json:   0%|          | 0.00/483 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

Tokenizer Loaded Successfully!


In [6]:
# Tokenize the flower descriptions

encoded_inputs = tokenizer(
    flower_descriptions,
    padding=True,
    truncation=True,
    return_tensors="pt"
)

print("Input IDs:\n")
print(encoded_inputs["input_ids"])

print("\nAttention Mask:\n")
print(encoded_inputs["attention_mask"])

Input IDs:

tensor([[  101,  1037,  2417,  3123,  2007,  2665,  3727,   102,     0,     0],
        [  101,  1037,  4408,  3756,  3103, 14156,  2104,  9325,   102,     0],
        [  101,  1037,  2317,  7094, 13426,  2075,  1999,  1037,  3871,   102],
        [  101,  1037,  5061, 13030,  8274,  2006,  2300,   102,     0,     0],
        [  101,  1037,  6379, 15573,  2007,  2146, 15829,   102,     0,     0]])

Attention Mask:

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 0, 0]])


In [7]:
# Load the pre-trained DistilBERT model

model = AutoModel.from_pretrained("distilbert-base-uncased")

print("DistilBERT Model Loaded Successfully!")

model.safetensors: reconstructing file:   0%|          |  0.00B /  268MB            

model.safetensors: downloading bytes:           |  0.00B            

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertModel LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |  | 
------------------------+------------+--+-
vocab_transform.bias    | UNEXPECTED |  | 
vocab_projector.bias    | UNEXPECTED |  | 
vocab_layer_norm.weight | UNEXPECTED |  | 
vocab_layer_norm.bias   | UNEXPECTED |  | 
vocab_transform.weight  | UNEXPECTED |  | 

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.


DistilBERT Model Loaded Successfully!


In [8]:
# Generate text embeddings

with torch.no_grad():
    outputs = model(**encoded_inputs)

embeddings = outputs.last_hidden_state

print("Embedding Shape:", embeddings.shape)
print("\nSample Embedding Vector:\n")
print(embeddings[0][0][:10])

Embedding Shape: torch.Size([5, 10, 768])

Sample Embedding Vector:

tensor([-0.3329, -0.1587,  0.0322, -0.1622, -0.1345, -0.0708,  0.1482,  0.5794,
        -0.0562, -0.1222])


## Integration of Text Embeddings into Image Generation Pipeline

The generated text embeddings are used as semantic representations of the textual descriptions. These embeddings are passed to the image generation model (Generator) to guide the image synthesis process.

Workflow:

Text Description
      ↓
Tokenizer
      ↓
Input IDs + Attention Mask
      ↓
DistilBERT
      ↓
Text Embeddings
      ↓
Generator (CGAN / Stable Diffusion)
      ↓
Generated Flower Image

In [9]:
# Simulated integration of embeddings into the image generation model

generator_input = embeddings.mean(dim=1)

print("Generator Input Shape:", generator_input.shape)

print("\nThe generated text embeddings are now ready to be passed")
print("to the image generation model.")

Generator Input Shape: torch.Size([5, 768])

The generated text embeddings are now ready to be passed
to the image generation model.


## Conclusion

In this task, flower descriptions were successfully preprocessed using Hugging Face Transformers.

The following steps were completed:

- Loaded flower descriptions
- Tokenized text using DistilBERT tokenizer
- Generated Input IDs and Attention Masks
- Created contextual text embeddings
- Prepared embeddings for the image generation pipeline

These embeddings serve as the semantic input for the text-to-image generation model.
